/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
import javax.swing.JOptionPane;
import java.awt.Color;


public class PertambahanDuaAngkaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PertambahanDuaAngkaFrame
     */
    public PertambahanDuaAngkaFrame() {
        initComponents();
        setLocationRelativeTo(null);

        // Menambahkan placeholder pada TextField1
        jTextAngka1.setText("Masukkan Angka 1");
        jTextAngka1.setForeground(Color.GRAY);

        // Menangani focus masuk dan keluar
        jTextAngka1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextAngka1.getForeground().equals(Color.GRAY) &&
                jTextAngka1.getText().equals("Masukkan Angka 1")) {
                jTextAngka1.setText("");
                jTextAngka1.setForeground(Color.BLACK);
            }
        }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextAngka1.getText().isEmpty()) {
                    jTextAngka1.setText("Masukkan Angka 1");
                 jTextAngka1.setForeground(Color.GRAY);
                }
            }
        });
        jTextFieldAngka2.setText("Masukkan Angka 2");
        jTextFieldAngka2.setForeground(Color.GRAY);

        jTextFieldAngka2.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextFieldAngka2.getText().equals("Masukkan Angka 2")) {
                    jTextFieldAngka2.setText("");
                    jTextFieldAngka2.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextFieldAngka2.getText().isEmpty()) {
                    jTextFieldAngka2.setText("Masukkan Angka 2");
                    jTextFieldAngka2.setForeground(Color.GRAY);
                }
            }
        });
        jTextFieldHasil.setText("Hasil Penjumlahan Akan Muncul Di Sini");
        jTextFieldHasil.setForeground(Color.GRAY);
        jTextFieldHasil.setEditable(false); // hasil tidak bisa diketik
        
        java.awt.EventQueue.invokeLater(() -> {
            jPanelTbhAngka.setFocusable(true);
            jPanelTbhAngka.requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTbhAngka = new javax.swing.JPanel();
        jLabelAngka1 = new javax.swing.JLabel();
        jTextAngka1 = new javax.swing.JTextField();
        jLabelAngka2 = new javax.swing.JLabel();
        jTextFieldAngka2 = new javax.swing.JTextField();
        jLabelHasil = new javax.swing.JLabel();
        jTextFieldHasil = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jLabelAplikasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pertambahan Dua Angka");
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(100, 80));

        jPanelTbhAngka.setBackground(new java.awt.Color(52, 73, 94));
        jPanelTbhAngka.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTbhAngka.setForeground(new java.awt.Color(255, 255, 255));

        jLabelAngka1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelAngka1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAngka1.setText("ANGKA 1");
        jLabelAngka1.setName(""); // NOI18N

        jTextAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAngka1ActionPerformed(evt);
            }
        });
        jTextAngka1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAngka1KeyTyped(evt);
            }
        });

        jLabelAngka2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAngka2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelAngka2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAngka2.setText("ANGKA 2");

        jTextFieldAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAngka2ActionPerformed(evt);
            }
        });
        jTextFieldAngka2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAngka2KeyTyped(evt);
            }
        });

        jLabelHasil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHasil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHasil.setText("HASIL");

        jTextFieldHasil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHasilKeyTyped(evt);
            }
        });

        jButtonTambah.setBackground(new java.awt.Color(39, 174, 96));
        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTambah.setText("TAMBAH");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(241, 196, 15));
        jButtonHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonKeluar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabelAplikasi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelAplikasi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAplikasi.setText("APLIKASI PERTAMBAHAN DUA ANGKA");

        javax.swing.GroupLayout jPanelTbhAngkaLayout = new javax.swing.GroupLayout(jPanelTbhAngka);
        jPanelTbhAngka.setLayout(jPanelTbhAngkaLayout);
        jPanelTbhAngkaLayout.setHorizontalGroup(
            jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTbhAngkaLayout.createSequentialGroup()
                .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTbhAngkaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAngka2)
                            .addComponent(jLabelAngka1)
                            .addComponent(jLabelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextAngka1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAngka2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldHasil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTbhAngkaLayout.createSequentialGroup()
                                .addComponent(jButtonTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelTbhAngkaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelAplikasi)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelTbhAngkaLayout.setVerticalGroup(
            jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTbhAngkaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAngka1)
                    .addComponent(jTextAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAngka2)
                    .addComponent(jTextFieldAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHasil)
                    .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelTbhAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonKeluar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelTbhAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelTbhAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAngka1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAngka1ActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin keluar dari aplikasi?",
        "Konfirmasi Keluar",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (pilihan == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi ini!");
        System.exit(0); // keluar jika pengguna memilih "Ya"
    } else {
        // jika memilih "Tidak", tidak melakukan apa-apa
    }
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
                // TODO add your handling code here:
                jTextAngka1.setText("Masukkan Angka 1");
                jTextAngka1.setForeground(Color.GRAY);
                jTextFieldAngka2.setText("Masukkan Angka 2");
                jTextFieldAngka2.setForeground(Color.GRAY);
                jTextFieldHasil.setText("Hasil Penjumlahan Akan Muncul Di Sini");
                jTextFieldHasil.setForeground(Color.GRAY);
                jTextAngka1.requestFocus();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        try {
            double angka1 = Double.parseDouble(jTextAngka1.getText());
            double angka2 = Double.parseDouble(jTextFieldAngka2.getText());
            double hasil = angka1 + angka2;
               jTextFieldHasil.setText(String.valueOf(hasil));
               jTextFieldHasil.setForeground(Color.BLACK);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!",
            "Error", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTambahActionPerformed
}
    private void jTextAngka1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAngka1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
        evt.consume(); // Menolak input non-angka
}
    }//GEN-LAST:event_jTextAngka1KeyTyped

    private void jTextFieldAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAngka2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldAngka2ActionPerformed

    private void jTextFieldAngka2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAngka2KeyTyped
        // TODO add your handling code here:
        {                                     
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
        evt.consume(); // Menolak input non-angka
}
    }                              
    }//GEN-LAST:event_jTextFieldAngka2KeyTyped

    private void jTextFieldHasilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHasilKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
        evt.consume(); // Menolak input non-angka
    }//GEN-LAST:event_jTextFieldHasilKeyTyped
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PertambahanDuaAngkaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelAngka1;
    private javax.swing.JLabel jLabelAngka2;
    private javax.swing.JLabel jLabelAplikasi;
    private javax.swing.JLabel jLabelHasil;
    private javax.swing.JPanel jPanelTbhAngka;
    private javax.swing.JTextField jTextAngka1;
    private javax.swing.JTextField jTextFieldAngka2;
    private javax.swing.JTextField jTextFieldHasil;
    // End of variables declaration//GEN-END:variables
}
